###
POST http://localhost:3000/api/courses
Content-Type: application/json

{
  "CourseName": "Intro",
  "Credits": 3,
  "Description": "Basic",
  "Semester": 1
}

###
GET http://localhost:3000/api/courses

###
GET http://localhost:3000/api/courses/1

###
PUT http://localhost:3000/api/courses/1
Content-Type: application/json

{
  "Credits": 4
}

###
DELETE http://localhost:3000/api/courses/1
